import 'package:flutter/material.dart';
import '../../core/network/api_client.dart';
import 'curriculum_page.dart';

class DashboardPage extends StatefulWidget { const DashboardPage({super.key,required this.api,required this.user}); final ApiClient api; final Map<String,dynamic> user; @override State<DashboardPage> createState()=>_DashboardPageState(); }
class _DashboardPageState extends State<DashboardPage>{List<dynamic> progress=[]; bool loading=true;
 @override void initState(){super.initState();load();}
 Future<void> load()async{try{progress=await widget.api.get('/learners/me/progress') as List<dynamic>;}catch(_){}if(mounted)setState(()=>loading=false);}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Mwalimu Hub KE'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.sync))]),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[Text('Welcome, ${widget.user['name']} 👋',style:const TextStyle(fontSize:26,fontWeight:FontWeight.bold)),const Text('Learn • Practice • Excel'),const SizedBox(height:20),GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:12,mainAxisSpacing:12,children:const[_Tile(icon:Icons.menu_book,title:'Learn',subtitle:'Lessons'),_Tile(icon:Icons.quiz,title:'Quiz',subtitle:'Practice'),_Tile(icon:Icons.trending_up,title:'Progress',subtitle:'Track growth'),_Tile(icon:Icons.workspace_premium,title:'Achievements',subtitle:'Badges')]),const SizedBox(height:24),Text('Recent learning',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:8),if(loading)const Center(child:CircularProgressIndicator()) else if(progress.isEmpty)const Card(child:ListTile(title:Text('No lessons completed yet'),subtitle:Text('Choose a subject and start learning today.'))) else ...progress.take(5).map((p)=>Card(child:ListTile(leading:const Icon(Icons.check_circle_outline),title:Text(p['lesson']?['titleEn']??'Lesson'),subtitle:Text('${p['percent']}% complete'))))]));}
}
class _Tile extends StatelessWidget{const _Tile({required this.icon,required this.title,required this.subtitle});final IconData icon;final String title,subtitle;@override Widget build(BuildContext c)=>Card(child:InkWell(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>CurriculumPage(api:widget.api))),child:Center(child:ListTile(leading:Icon(icon,size:30),title:Text(title,fontWeight:FontWeight.bold),subtitle:Text(subtitle)))));}
